"""init

Revision ID: 200975f9b340
Revises: cf760011bcda
Create Date: 2026-08-04 01:55:36.285296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200975f9b340'
down_revision: Union[str, Sequence[str], None] = 'cf760011bcda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_album_cover_photo', 'albums', 'photos', ['cover_photo_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_album_cover_photo', 'albums', type_='foreignkey')
    # ### end Alembic commands ###
