"""empty message

Revision ID: cf760011bcda
Revises: 4cae90a85f77
Create Date: 2026-08-03 20:32:59.946348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf760011bcda'
down_revision: Union[str, Sequence[str], None] = '4cae90a85f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "photos",
        sa.Column(
            "media_type",
            sa.String(length=10),
            nullable=False,
            server_default="image",
        ),
    )
    # опційно прибрати default після заповнення
    op.alter_column("photos", "media_type", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'media_type')
    op.drop_constraint('fk_album_cover_photo', 'albums', type_='foreignkey')
    # ### end Alembic commands ###
